#FROM drouhana/envoy-oqs:envoy-oqs-base
FROM drouhana/envoy-oqs:envoy

COPY ./envoy-frontend.yaml /etc/example/envoy.yaml
COPY ./certs/CA_cert.pem /etc/example/cacert.pem
COPY ./certs/localhost-frontend.pem /etc/example/clientcert.pem
COPY ./certs/localhostkey.pem /etc/example/clientkey.pem

WORKDIR /etc/example
RUN chown "$USER" -R *

RUN chmod go+r /etc/example/envoy.yaml 
RUN chmod go+r /etc/example/cacert.pem 
RUN chmod go+r /etc/example/clientkey.pem 
RUN chmod go+r /etc/example/clientcert.pem

#CMD ["envoy-static", "-c /etc/example/envoy.yaml"]
CMD ["envoy", "-c /etc/example/envoy.yaml"]