 # Define global arguments
ARG DEBIAN_FRONTEND=noninteractive

FROM drouhana/envoy-oqs:envoy

# copy certs
COPY ./certs/servercert.pem /etc/example/servercert.pem
COPY ./certs/serverkey.pem /etc/example/serverkey.pem
COPY ./front-envoy.yaml /etc/example/front-envoy.yaml


WORKDIR /etc/example
RUN chown "$USER" -R *

RUN chmod go+r /etc/example/servercert.pem
RUN chmod go+r /etc/example/serverkey.pem
RUN chmod go+r /etc/example/front-envoy.yaml


CMD ["envoy", "-c", "/etc/example/front-envoy.yaml", "--service-cluster", "front-proxy"]
