version: "3.7"
services:

  flask_service:
    build:
      context: ../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "off"
    deploy:
      replicas: 0

  proxy-frontend:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      edge:
    ports:
    - "10000:10000"

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      edge:
      postgres-frontend:
    volumes:
    - ./service.py:/code/service.py

  proxy-postgres-frontend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-frontend
    networks:
      postgres-frontend:
        aliases:
        - localhost-frontend
      postgres-in-between:

  proxy-postgres-backend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-backend
    networks:
      postgres-backend:
      postgres-in-between:
        aliases:
        - localhost-backend

  postgres:
    build:
      context: ../shared/postgres
    networks:
      postgres-backend:
    environment:
      # WARNING! Do not use it on production environments because this will
      #          allow anyone with access to the Postgres port to access your
      #          database without a password, even if POSTGRES_PASSWORD is set.
      #          See PostgreSQL documentation about "trust":
      #          https://www.postgresql.org/docs/current/auth-trust.html
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  edge:
    name: edge

  postgres-backend:
    name: localhost-backend

  postgres-frontend:
    name: localhost-frontend

  postgres-in-between:
    name: postgres-in-between
